### ISSUE TITLE
doesn't work with setInterval()

### ISSUE THREAD

**Issue by heathblandford** [heathblandford/gus#1]
in `gus.js` the `checkStreamers` function runs, but it doesn't run in a `setInterval()`. 

here's the error: 

```timers.js:531
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at exports.setInterval (timers.js:531:11)
    at Object.<anonymous> (/home/heath-laptop/Programming/projects/gus/src/gus.js:19:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 5.0.0-27-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gus@1.0.0 start: `node src/gus.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gus@1.0.0 start script 'node src/gus.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/gus.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/heath-laptop/Programming/projects/gus/npm-debug.log```

**Comment by heathblandford** [comment]
Issue was in `checkStreamers` function. 

was `module.exports = runIt();`

and now is `module.exports = runIt;`

Same thing for the `setInterval`. Need to use `setInterval(checkStreamer, 60*1000*1)` instead of using the function call: `setInterval(checkStreamers(), 60*1000*1)`. 

Everything works now :)
